apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx
  namespace: nginx
spec:
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: /storage/nginx
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-claim
  namespace: nginx
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 100Mi