apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: nginx-http-port
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30082
    - name: nginx-https-port
      protocol: TCP
      port: 443
      targetPort: 443